import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className='flex justify-between items-center px-20 mt-10'>
          <h2 className='text-4xl font-bold '>Seb Explorer</h2>
          <nav>
            <ul>
              <li><Link href={'/'}>Home</Link></li>
            </ul>
          </nav>

        </header>

        {children}
        </body>
    </html>
  )
}
